version: '3.4'

services:
  nginx:
    image: nginx:latest
    volumes:
      - "/etc/nginx:/etc/nginx"
    ports:
      - "4200:4200"
      - "4231:4231"
      - "4232:4232"
      - "4233:4233"
      - "4234:4234"
      - "4235:4235"
      - "4236:4236"
      - "4237:4237"
  applicant-tracking:
    image: blens/at:latest
    ports:
      - '3237:80'
  client-management:
    image: blens/cm:latest
    ports:
      - '3235:80'
  project-management:
    image: blens/pm:latest
    ports:
      - '3236:80'
  timesheet:
    image: blens/ts:latest
    ports:
      - '3233:80'
  resource-management:
    image: blens/rm:latest
    ports:
      - '3234:80'
  usermanagement:
    image: blens/um:latest
    ports:
      - '3231:80'
  configurationmodule:
    image: blens/configuration
    ports:
      - '3232:80'
  epp-dashboard:
    image: blens/epp-dash
    ports:
      - '3200:80'